var roms = [
'2Pak Black - Challenge - Surfing.bin',
'2Pak Green - Hoppy - Alien Force.bin',
'2Pak Yellow - Star Warrior - Frogger.bin',
'32-in-1 (PAL).bin',
'3D Tic-Tac-Toe (1).bin',
'3D Tic-Tac-Toe (2).bin',
'3D Tic-Tac-Toe (32 in 1) (PAL).bin',
'Acid Drop.bin',
'Action Man.bin',
'Adventure.bin',
'Adventures of Tron.bin',
'AdventuresOnGX12.BIN',
'Airlock.bin',
'Air Raid.bin',
'Air Raiders.bin',
'Air-Sea Battle (1).bin',
'Air-Sea Battle (2).bin',
'Air-Sea Battle (32 in 1) (PAL).bin',
'Alien.bin',
'Alien\'s Return.bin',
'AlligatorPeople.bin',
'Alpha Beam with Ernie.bin',
'Amidar.bin',
'A Misterious Thief (CCE).bin',
'Angling.bin',
'Apples and Dolls (CCE).bin',
'Aquaventure.bin',
'Armor Ambush.bin',
'Artillery Duel (1).bin',
'Assault.bin',
'Asterix.bin',
'ASTEROID.BIN',
'Asteroids.bin',
'ASTRBLST.BIN',
'Astroblast.bin',
'Astrowar.bin',
'Astro War.bin',
'Atari 2600 Invaders (hack).bin',
'Atari Video Cube.bin',
'A-Team.bin',
'Atlantis2.BIN',
'Atlantis (Activision) (1).bin',
'Autorennen (Grand Prix).bin',
'Bachellorette Party.bin',
'Bachelor.bin',
'backfire.bin',
'Backgammon.bin',
'Bank Heist.bin',
'Barnstorming.bin',
'Base Attack (PAL).bin',
'Basic Programming.bin',
'Basketball (32 in 1) (PAL).bin',
'Basketball (4k version).bin',
'Battlezone.bin',
'Beamrider (2).bin',
'Beany Bopper.bin',
'Beat \'Em and Eat \'Em.bin',
'Berenstain Bears (Coleco).bin',
'Bermuda.bin',
'Bermuda Triangle.bin',
'Berzerk.bin',
'berzerkvoice.bin',
'Bi! Bi! (PAL).bin',
'Big Bird\'s Egg Catch.bin',
'Bionic Breakthrough.bin',
'Blackjack (1).bin',
'Blackjack (2).bin',
'Blackjack (32 in 1) (PAL).bin',
'BloodyHumanFreeway_NTSC.bin',
'Blueprint.bin',
'BMX Airmaster.bin',
'Bobby is Going Home (CCE).bin',
'Bogey Blaster.bin',
'Boggle.bin',
'Boing! (alt 1) (PD).bin',
'Boing! (PD).bin',
'Boom Bang.bin',
'Bowling (1).bin',
'Bowling (2).bin',
'Bowling (32 in 1) (PAL).bin',
'Bowling (4k version).bin',
'Boxing (1).bin',
'Boxing (2).bin',
'Boxing (32 in 1) (PAL).bin',
'Brain Games (1).bin',
'Brain Games (2).bin',
'Breakdown.bin',
'Breakout - Breakaway IV (1).bin',
'Breakout - Breakaway IV (2).bin',
'Brick Kick.bin',
'Bridge.bin',
'Buck Rogers - Planet of Zoom.bin',
'Bugs.bin',
'Bugs Bunny.bin',
'Bumpnjump.bin',
'Burgertime.bin',
'Burning Desire.bin',
'Cakewalk.bin',
'California Games.bin',
'Canyon Bomber (4k version).bin',
'Carnival.bin',
'Casino.bin',
'Cathouse Blues.bin',
'Catmouse.bin',
'Cat Trax.bin',
'Centipede.bin',
'Challenge (Alt).bin',
'Challenge of...NEXAR.bin',
'Chase the Chuckwagon.bin',
'Checkers (32 in 1) (PAL).bin',
'Checkers (Activision).bin',
'China Syndrome.bin',
'Chopper Command (CCE).bin',
'Chuckick.bin',
'Chuck Norris Superkicks.bin',
'Chuckwgn.bin',
'Circus Atari.bin',
'Circus-j.bin',
'climber5_NTSC.bin',
'Clown Downtown (PAL).bin',
'Coconuts.bin',
'Code Breaker (1).bin',
'Code Breaker (2).bin',
'Coke Wins.bin',
'Coln.bin',
'Color Bar Generator.bin',
'Colors Demo.bin',
'combat2.bin',
'Combat (32 in 1) (PAL).bin',
'Combat - Tank Plus (4k Version).bin',
'Commando.bin',
'Commando Raid.bin',
'Concentration.bin',
'Condor Attack.bin',
'CONDOR.BIN',
'confrontation.bin',
'Congbong.bin',
'Congo Bongo.bin',
'Conquest of Mars.bin',
'Cookie Monster Munch.bin',
'Corrida da Matematica (CCE).bin',
'Cosmic Ark (CCE).bin',
'Cosmic Commuter.bin',
'Cosmic Corridor.bin',
'Cosmic Creeps.bin',
'Cosmic Swarm (32 in 1) (PAL).bin',
'Cosmic Swarm (4k Version).bin',
'Cosmic Swarm.bin',
'Cracked.BIN',
'Crackpots.bin',
'Crash Dive.bin',
'crazyballoon-ntsc.bin',
'Crazy Climber.bin',
'CrazyValet.bin',
'Criminal Pursuit.bin',
'Crossbow.bin',
'Cross Force.bin',
'Cruise Missile.bin',
'Crusmisl.bin',
'Crypts of Chaos.bin',
'Crystal Castles.bin',
'Cubicolor.bin',
'Cubo Magico (CCE).bin',
'Custerev.bin',
'Dancing Plate (PAL).bin',
'Darkcham.bin',
'Darkcvrn.bin',
'darkmage.bin',
'Deadly Duck.bin',
'Death Trap.bin',
'Decathlon.bin',
'Defender 2 (16K version).bin',
'Defender 2.bin',
'Defender.bin',
'Demolition Herby.bin',
'Demon Attack (Activision).bin',
'Demons to Diamonds.bin',
'Desert Falcon.bin',
'Dethstar.bin',
'Dice Puzzle.bin',
'Dig Dug.bin',
'Dishastr.bin',
'Dodge Em.bin',
'Dolphin.bin',
'Donald Duck\'s Speedboat.bin',
'Donkey Kong.bin',
'Donkey Kong Jr. (CCE).bin',
'Double Dragon.bin',
'Double Dunk.bin',
'Dragon Defender.bin',
'Dragonfire.bin',
'Dragster (1).bin',
'Dragster (2).bin',
'Drgndfnd.bin',
'Dschungle Boy (Pitfall).bin',
'Duck Shoot (PAL).bin',
'Dukes of Hazzard.bin',
'dukes_v2.bin',
'Dumbo\'s Flying Circus.bin',
'dune.bin',
'Earth Dies Screaming.bin',
'Eggomania.bin',
'ElevatorAction.bin',
'Eliladdr.bin',
'Elk Attack.bin',
'Encounter at L5.bin',
'Enduro.bin',
'Entity.BIN',
'Entombed.bin',
'Espial.bin',
'E.T..bin',
'Euchre.bin',
'EuchrePAL.bin',
'Ewok Adventure (Parker Bros, Thomas Jentzsch) (NTSC).bin',
'Ewokadvn.bin',
'Exocet.bin',
'F-14 Tomcat Flight Simulator.bin',
'falldown_ntsc.bin',
'Fantastic Voyage.bin',
'Farmyard Fun.bin',
'Fast Eddie.bin',
'Fast Food.bin',
'Fatal Run.bin',
'Fathom.bin',
'Fighterp.bin',
'Final Approach.bin',
'Fire Birds.bin',
'Fire Fighter.bin',
'Fire Fly.bin',
'Fire Spinner.bin',
'Fishing Derby (16k Version).bin',
'Fishing Derby (32 in 1) (PAL).bin',
'Fishing Derby (pirate) (32 in 1) (PAL).bin',
'Flag Capture (32 in 1) (PAL).bin',
'Flag Capture.bin',
'FlapPing.bin',
'Flash Gordon.bin',
'Flashgrd.bin',
'Football (1).bin',
'Football (2).bin',
'Football (32 in 1) (PAL).bin',
'Foozball.bin',
'Forest (PAL).bin',
'fotr.bin',
'Frankenstein\'s Monster.bin',
'Freeway (1).bin',
'Freeway (2).bin',
'Freeway (32 in 1) (PAL).bin',
'Freeway (pirate) (32 in 1) (PAL).bin',
'Frogflys.bin',
'Frogger.bin',
'Frogger II - Threedeep!.bin',
'Frogpond.bin',
'Frontline.bin',
'Frostbite.bin',
'Fun with Numbers (32 in 1) (PAL).bin',
'Fun With Numbers.bin',
'Galaga.bin',
'Galaxian.bin',
'Game of Concentration.bin',
'Gangster Alley.bin',
'garfield.bin',
'Gas Hog.bin',
'Gauntlet.bin',
'Ghostbusters.bin',
'Ghostbusters II.bin',
'Ghostman.bin',
'Ghost Manor (1).bin',
'Ghost Manor (2).bin',
'Gigolo.bin',
'G.I. Joe - Cobra Strike.bin',
'Glacier Patrol.bin',
'Glib.bin',
'GoFish_NTSC.bin',
'Golf (1).bin',
'Golf (2).bin',
'Golf (32 in 1) (PAL).bin',
'Golf.bin',
'Gopher.bin',
'Gorf.bin',
'Grand Prix (16k Version).bin',
'Gravitar.bin',
'Great Escape.bin',
'Gremlins.bin',
'Grover\'s Music Maker.bin',
'Guardian.bin',
'GUNNTSC.bin',
'Gyruss.bin',
'Halloween.bin',
'Hangman.bin',
'Harbor Escape.bin',
'Haunted House.bin',
'H.E.R.O..bin',
'Hole Hunter.bin',
'Holey Moley.bin',
'Homerun (32 in 1) (PAL).bin',
'Home Run Baseball (1).bin',
'Home Run Baseball (2).bin',
'Human Cannonball (32 in 1) (PAL).bin',
'Human Cannonball - Cannon Man (1).bin',
'Human Cannonball - Cannon Man (2).bin',
'Ice Hockey.bin',
'Ikari Warriors.bin',
'Imagic Selector.bin',
'Immies and Aggies.bin',
'IncaGold_Zellers.BIN',
'Indy 500 (4k Version).bin',
'Infiltrate.bin',
'International Soccer.bin',
'INV.bin',
'INV+.bin',
'Iq180.bin',
'I.Q. 180.bin',
'I Want My Mommy.bin',
'Ixion.bin',
'James Bond 007.bin',
'Jammed.bin',
'Jawbreaker.bin',
'Jediaren.bin',
'Journey Escape.bin',
'Joust.bin',
'JoustPong.bin',
'Jrpacman.bin',
'Jungle Fever.bin',
'Jungle Hunt.bin',
'Kaboom! (1).bin',
'Kaboom! (2).bin',
'kamisauc.bin',
'Kangaroo.bin',
'Karate.bin',
'Keystone Kapers.bin',
'King Kong.bin',
'Klax.bin',
'Knight on the Town.bin',
'Kool Aid Man.bin',
'Krull.bin',
'Kung Fu.bin',
'Kung Fu Master.bin',
'labyrinth.bin',
'Lady in Wading.bin',
'Laser Blast (1).bin',
'Laser Blast (2).bin',
'Laser Blast (32 in 1) (PAL).bin',
'Laser Gates.bin',
'LASRGATE.BIN',
'Lasrvoly.bin',
'lochjaw.bin',
'Lock n Chase.bin',
'London Blitz.bin',
'Looping.BIN',
'LordOfTheRings.bin',
'LOSTLUGG.BIN',
'M.A.D..bin',
'magicard.bin',
'Malagai.bin',
'Mangia.bin',
'Marauder.bin',
'Marineflieger (PAL).bin',
'Marine Wars.bin',
'MARIOBRO.BIN',
'M.A.S.H..bin',
'Master Builder.bin',
'Masters of the Universe - The Power of He-Man.bin',
'Math Gran Prix.bin',
'Maze Craze.bin',
'McDonalds.bin',
'mc_ntsc_7_26_3.bin',
'mc_pal_4_28_3.bin',
'Mega Force.bin',
'Megamania.bin',
'Meltdown.bin',
'Meteor Defence.bin',
'Midnight Magic.bin',
'Millipede.bin',
'MindMaze.bin',
'Miner 2049er.bin',
'Mines of Minos.bin',
'Minesweeper.bin',
'MIN_GOLF.BIN',
'Miniature Golf (32 in 1) (PAL).bin',
'Miniature Golf - Arcade Golf (1).bin',
'Miniature Golf - Arcade Golf (2).bin',
'MINRVOL2.BIN',
'Missile Command.bin',
'Missile Control.bin',
'Mission 3000 A.D..bin',
'Misspig.bin',
'Mogul Maniac.bin',
'MondoPong.bin',
'Monstercise.bin',
'Montezuma\'s Revenge.bin',
'Moon Patrol.bin',
'Moonsweeper.bin',
'Motocross.bin',
'Motocross Racer.bin',
'Motocross Racer - Joystik.bin',
'Moto Laser (CCE).bin',
'Motorodeo.bin',
'Mouse Trap.bin',
'Mr. Do!.bin',
'Mr. Do!\'s Castle.bin',
'Mr. Postman.bin',
'Ms. Pac-Man.bin',
'MTNKING.BIN',
'Multi-Sprite Demo.bin',
'Music Machine.bin',
'My Golf.bin',
'NAMEGAME.BIN',
'Nexar.bin',
'NGHTMARE.BIN',
'Night Driver (4k Version).bin',
'Nightmare.bin',
'Night Stalker.bin',
'No Escape! (1).bin',
'Nuts.bin',
'Obelix.bin',
'Ocean City Defender.bin',
'Octopus.bin',
'Off Your Rocker.bin',
'Ofthwall.bin',
'Oink!.bin',
'Okie Dokie.bin',
'Omegarac.bin',
'Open Sesame.bin',
'Oscar\'s Trash Race.bin',
'Othello (32 in 1) (PAL).bin',
'Outerspc.bin',
'Outlaw (32 in 1) (PAL).bin',
'Outlaw - GunSlinger (2).bin',
'Out of Control.bin',
'Oystron.bin',
'Pac Kong.bin',
'Pac-Man.bin',
'Pac-Man (hack).BIN',
'Pac-Space.bin',
'Panda Chase.bin',
'Parachute.bin',
'Peek-A-Boo.bin',
'Pele.bin',
'Pele\'s Championship Soccer.bin',
'Pele\'s Championship Soccer (pirate).bin',
'Pengo.bin',
'Pete Rose Baseball.bin',
'phantompanzer.bin',
'Phantom Tank (PAL).bin',
'Pharoah\'s Curse.bin',
'Philly Flasher.bin',
'Phoenix.bin',
'Pick \'n Pile.bin',
'PickUp.BIN',
'Picnic.bin',
'Piece o\' Cake.bin',
'Pigs in Space.bin',
'Pitfall! (Beta).bin',
'Pitfall!.bin',
'Pitfall II - Lost Caverns (10K version).bin',
'Pitfall! No Walls Hack.bin',
'PizzaChef.bin',
'PlanetOfTheApes.bin',
'Planet Patrol.bin',
'Plaque Attack.bin',
'Pleiades.bin',
'poker_squares.bin',
'Polaris.bin',
'Pole Position.bin',
'Polo.bin',
'Pompeii.bin',
'Pooyan.bin',
'Popeye.bin',
'Porky\'s.bin',
'pressgge.bin',
'Pressure Cooker.bin',
'Private Eye.bin',
'Puzzle (Taiwan).bin',
'Pyramid War.bin',
'qb215NTSC.bin',
'qb215PAL.bin',
'qb215STELLA.bin',
'Q-bert.bin',
'Q-bert\'s Qubes (2).bin',
'Quadrun.bin',
'Quest for Quintana Roo.bin',
'Quick Step!.bin',
'Rabbittr.bin',
'Racquetball.bin',
'Radarlok.bin',
'Raft Rider.bin',
'Raiders of the Lost Ark.bin',
'Rainbow Invaders NTSC.bin',
'Ram It.bin',
'Rampage!.bin',
'Reactor.bin',
'RealSports Baseball.bin',
'RealSports Boxing.bin',
'RealSports Football.bin',
'RealSports Soccer.bin',
'RealSports Tennis (1).bin',
'RealSports Volleyball.bin',
'Rescue Bira Bira.bin',
'Rescue Terra I.bin',
'Resgate Espacial (CCE).bin',
'RevengeOfTheApes.bin',
'Revenge of the Beefsteak Tomatoes.bin',
'Riddle of the Sphinx.bin',
'River Patrol.bin',
'River Raid (16k Version).bin',
'River_tw.bin',
'Rivraid2.bin',
'Road Runner.bin',
'Robin Hood.bin',
'robnhood.bin',
'Robot Fight.bin',
'Robot Tank.bin',
'Roc n\' Rope.bin',
'Room of Doom.bin',
'RubiksCube3D.bin',
'RushHour.BIN',
'Saboteur.bin',
'sagent.bin',
'SaveMary_NTSC.bin',
'Save Our Ship.bin',
'SaveTheWhales.BIN',
'scsi130-cge2k1.bin',
'scsi130sp-cge2k1.bin',
'scsi200_NTSC.bin',
'SCUDIV_P.BIN',
'Sea Hawk (CCE).bin',
'Sea Hunt.bin',
'Sea Monster (PAL).bin',
'seantsc.bin',
'Seaquest.bin',
'SECRETQ.BIN',
'Seesaw (Taiwan).bin',
'Sentinel.bin',
'Shark Attack.bin',
'shootacd.bin',
'Shootin\' Gallery.bin',
'Shuttle Orbiter.bin',
'Sinistar.bin',
'Sir Lancelot.bin',
'Skateboardin\'.bin',
'Skeet Shoot (1).bin',
'Skeet Shoot (2).bin',
'skeleton.bin',
'skel-pal.bin',
'SkelPlus.bin',
'SkelPPAL.bin',
'Ski Hunt.bin',
'Skiing (1).bin',
'Skiing (2).bin',
'Skiing (32 in 1) (PAL).bin',
'Ski Run.bin',
'Sky Diver (32 in 1) (PAL).bin',
'Sky Diver.bin',
'Sky Jinks (4k version).bin',
'Sky Patrol (Prototype).bin',
'Sky Skipper.bin',
'Slot Machine (32 in 1) (PAL).bin',
'Slot Machine.bin',
'Slot Racers (32 in 1) (PAL).bin',
'Slot Racers - Maze (1).bin',
'Slot Racers - Maze (2).bin',
'SMRFSAVE.BIN',
'Smurfs - Rescue in Gargamel\'s Castle.bin',
'Snail Against Squirrel (CCE).bin',
'Sneek n Peek.bin',
'Snoopy and the Red Baron.bin',
'snow_wht.bin',
'snthcart.bin',
'Soccer (Unlicensed).bin',
'Solar Fox.bin',
'Solaris.bin',
'SolarPlexus.bin',
'Solar Storm.bin',
'Sorcerer.bin',
'Sorcerer\'s Apprentice.bin',
'SpaceAdventure_Zellers.BIN',
'Space Attack.bin',
'Space Canyon.bin',
'Space Cavern.bin',
'Spacechase.bin',
'Space Invaders.bin',
'Space Invaders (hack).BIN',
'Space Jockey (32 in 1) (PAL).bin',
'Space Jockey (4K version).bin',
'Space Jockey.bin',
'SpaceMaster X-7.bin',
'Space Raid.bin',
'Space Robot.bin',
'Space Shuttle.bin',
'Space Tunnel (PAL).bin',
'Space Tunnel (Taiwan).bin',
'Space War (32 in 1) (PAL).bin',
'Space War (4k Version).bin',
'Space War.bin',
'SP-DL.BIN',
'Spiderdroid.bin',
'Spider Fighter (16k Version).bin',
'Spider Fighter.bin',
'Spider-Man.bin',
'spidermz.BIN',
'Spike\'s Peak.bin',
'Spitfire Attack.bin',
'Springer.bin',
'Sprintmaster.bin',
'Spy Hunter.bin',
'Squeeze Box.bin',
'Squoosh.bin',
'Sssnake.bin',
'Stampede (1).bin',
'Stampede (2).bin',
'Stampede (32 in 1) (PAL).bin',
'STAREMPR.BIN',
'Star Fox.bin',
'Stargate (1).bin',
'STARGN.BIN',
'Starmaster.bin',
'Starpath - Communist Mutants From Space.bin',
'Starpath - Dragonstomper.bin',
'Starpath - Escape from the Mindmaster.bin',
'Starpath - Fireball.bin',
'Starpath - Frogger (Official version by Sega).bin',
'Starpath - Killer Satellites.bin',
'Starpath - Party Mix.bin',
'Starpath - Phaser Patrol.bin',
'Starpath - Rabbit Transit.bin',
'Starpath - Suicide Mission.bin',
'Starpath - Survival Island.bin',
'Starpath - Sweat! - The Decathalon Game.bin',
'Starpath - Sword Of Saros.bin',
'Star Raiders.bin',
'Star Ship - Outer Space (1).bin',
'Star Ship - Outer Space (2).bin',
'Star Strike.bin',
'STARTREK.BIN',
'Star Trek - Strategic Operations Simulator.bin',
'Star Voyager.bin',
'STARVYGR.BIN',
'Star Wars - Death Star Battle.bin',
'Star Wars - Empire Strikes Back.bin',
'Star Wars - Jedi Arena.bin',
'Star Wars - The Arcade Game.bin',
'Steeplechase (1).bin',
'Steeplechase (2).bin',
'Stellar Track.bin',
'Stell-A-Sketch.bin',
'Stntman.bin',
'Strategy X.bin',
'StratOGemsDeluxe.bin',
'Strawberry Shortcake Musical Match-Ups.bin',
'Street Racer - Speedway II (2).bin',
'Stronghold.bin',
'stunt.bin',
'Submarine Commander.bin',
'Sub Scan.bin',
'Subterrenea.bin',
'Summer Games.bin',
'Super Baseball.bin',
'Super Box (CCE).bin',
'Super Breakout.bin',
'Super Challenge Baseball.bin',
'Super Challenge Football.bin',
'Super Cobra.bin',
'Super Ferrari.bin',
'Super Futebol.bin',
'Superman (1).bin',
'Suprman2.bin',
'Surfer\'s Paradise - But Danger Below!.bin',
'Surf\'s Up.bin',
'Surround (32 in 1) (PAL).bin',
'Surround (4k version).bin',
'Survival Run.bin',
'SWARCADE.BIN',
'Swoops! (v0.96).bin',
'Swoops! (v0.96) (PAL).bin',
'SwordQuest - Earthworld.bin',
'SwordQuest - Fireworld.bin',
'SwordQuest - Waterworld.bin',
'Tacscan.bin',
'Tanks But No Tanks.bin',
'Tapeworm.bin',
'Tapper.bin',
'Targ (CBS).bin',
'Task Force.bin',
'Tax Avoiders.bin',
'Taz.bin',
'Teddy Apple.bin',
'telepathy.bin',
'tempst26.bin',
'Tennis (1).bin',
'Tennis (2).bin',
'Tennis (32 in 1) (PAL).bin',
'Test.bin',
'testcart.bin',
'Tetris 2600.bin',
'Texas Chainsaw Massacre.bin',
'T.F. Space Invaders.bin',
'This Planet Sucks.bin',
'Threshhold.bin',
'Thrust.bin',
'Thrust+.bin',
'Thrust v1.26 (PD).bin',
'Thunderground.bin',
'Time Machine.bin',
'Time Pilot (1).bin',
'Time Race.bin',
'Time Warp.bin',
'Title Match Pro Wrestling (1).bin',
'Tomarc the Barbarian.bin',
'Tom Boy.bin',
'Tooth Protectors.bin',
'Towering Inferno.bin',
'Tps.bin',
'Track and Field.bin',
'Traffic.bin',
'Treasure Below (Video Gems, Thomas Jentzsch) (NTSC).bin',
'treat.bin',
'treat_ntsc.bin',
'Trick Shot.bin',
'Tron - Deadly Discs.bin',
'Tuby Bird.bin',
'Tunlrunr.bin',
'Turmoil.bin',
'Tutankham.bin',
'UFO Patrol.bin',
'Universal Chaos (PAL).bin',
'UniversalProto.Bin',
'UnknownActivision1_NTSC.bin',
'UnknownActivision2_NTSC.bin',
'Up n Down.bin',
'Vanguard.bin',
'VaultAssault.bin',
'VenetianBlinds_NTSC.bin',
'Venture.bin',
'Vg_survi.bin',
'Video Checkers.bin',
'Video Chess.bin',
'Video Cube (CCE).bin',
'Video Jogger.bin',
'Video Olympics - Pong Sports (1).bin',
'Video Olympics - Pong Sports (2).bin',
'Video Pinball.bin',
'Video Reflex.bin',
'Video Time Machine.bin',
'Vidpin.bin',
'VultureAttack_KTel.bin',
'Wabbit.bin',
'Walker.bin',
'Wall Ball.bin',
'Wall Defender.bin',
'Warlords.bin',
'Warplock.bin',
'warworm.bin',
'Weltraum Tunnel.bin',
'Wings_6-3-83.bin',
'Wing War.bin',
'Winter Games.bin',
'Wizard.bin',
'Wizard of Wor.bin',
'words.bin',
'Word Zapper.bin',
'World End.bin',
'Worm War I.bin',
'X-Doom.bin',
'Xenophob.bin',
'Xevious.bin',
'X-Man (1).bin',
'Yahtzee.bin',
'Yar\'s Revenge (1).bin',
'Zaxxon.bin',
'Zoo Fun.bin',
'Z-Tack.bin'
];

var romList = $('select#rom-list');
var listItems = '<option value="">Or load one from the catalog (722 roms!)</option>';
for (var i = 0; i < roms.length; i++) {
  listItems += '<option value="' + roms[i] + '">' + roms[i] + '</option>';
}
romList.append(listItems);

$('ul.favorites a').click(function(e) {
  e.preventDefault();
  loadGame($(this).attr('href'));
});

$('button#load').click(function(e) {
  var choice = romList.val();
  if(choice != '') {
    loadGame(choice);
  }
});

function loadGame(name) {
  var url = location.origin + location.pathname + 'roms/';
  Javatari.room.romLoader.loadFromURL(url+name);
}
